### ISSUE TITLE
mymap js Draggble nodes 

### ISSUE THREAD

**Issue by sankar-wa** [ondras/my-mind#102]
Hi ondras,
I have used this my-mind.js template and its working excellent, 
But a most important feature I missed that I am not able to move the nodes freely around anywhere. Only it can be separated from node to another node.I checked that the whole node links are in a single canvas , 
Can you please help me that how can I drag the nodes freely with flexible node links like below example ?
https://gojs.net/latest/samples/mindMap.html

**Comment by ondras** [comment]
Hi @sankar-wa,

unfortunately, the automatic placement of nodes is one of MyMind's major invariants. There is really no support for manual placement and this design decision is deliberate.

If you allow users to freely drag nodes, you essentially introduce the possibility of overlap. My Mind is designed in a way that overlap is not possible.
