### ISSUE TITLE
Feature: Change language

### ISSUE THREAD

**Issue by dataarchivist** [ondras/my-mind#103]
Its may a good idea, if the user can change it? :)
And a big thanks for your work!

**Comment by ondras** [comment]
There is no localization support. Most strings, however, are statically defined inside `index.html`, so perhaps adding some rudimentary i10n stuff might not be that hard.

I am completely out of time these days, so implementing said features can only be done in a form of a PR.

**Comment by dataarchivist** [comment]
Oh no worries, I am not in a rush. Have a great christmas holiday and may you have next year the time for this. :)
