### ISSUE TITLE
macbook keyboard shortcut to delete item (delete key not working)

### ISSUE THREAD

**Issue by zainengineer** [ondras/my-mind#105]
macbook has delete button which is labeled as delete but is equivalant to windows/linux backspace button

can you make backspace do the delete as well if OS is mac?

**Comment by ondras** [comment]
Hi @zainengineer,

to clarify: hitting the said button generates `keyCode: 8` ?

**Comment by zainengineer** [comment]
@ondras sorry missed the notification
yes `keyCode: 8` checked it using
https://keycode.info/

**Comment by ondras** [comment]
So, well, I *can* make your button do delete stuff, but what about the `backspace` key (that selects a parent node right now)? Do you suggest not binding this combination on MacOS at all?

**Comment by zainengineer** [comment]
@ondras My suggestion will to keep the backspace as well
As sometime developers use external keyboards which have both delete and backspace (like normal keyboards)

**Comment by ondras** [comment]
> @ondras My suggestion will to keep the backspace as well

I would love to! But according to your report, I have no clue how to distinguish between a backspace and your special delete key, as both of them generate the same keyCode.

**Comment by zainengineer** [comment]
@ondras is it possible to trigger delete action on both backspace and delete button?

**Comment by ondras** [comment]
> @ondras is it possible to trigger delete action on both backspace and delete button?

Yes. But you lose the current "backspace" function (select a parent node), because the keyCode generated by backspace (8) will be re-assigned to node deletion, so that your special delete button deletes nodes :-)

**Comment by zainengineer** [comment]
@ondras can we have two keys for same action
I had a quick look at code, And it seems there are few commands which have multiple keyboard shortcuts for example Side Command.
can we do something like that for delete? have both backspace and delete key for that command.

**Comment by ondras** [comment]
> @ondras can we have two keys for same action

Yes, that is easy.

The issue here is that the `backspace` key (or, more precisely, the keyCode of 8) is already used by a different functionality. If we re-assign keyCode 8 to `delete node`, we will be able to delete nodes by backspace, but we well lose the `hit backspace to go up` feature.

**Comment by zainengineer** [comment]
this makes it very tricky.

Only wayout I can think of is to not have `hit backspace to go up` feature in mac
as backspace keycode might be delete keycode on mac

**Comment by ondras** [comment]
> Only wayout I can think of is to not have `hit backspace to go up` feature in mac
> as backspace keycode might be delete keycode on mac

Right, that is what I was asking for in https://github.com/ondras/my-mind/issues/105#issuecomment-584498140. I conclude that the requested change is to map `keyCode 8` do `delete node` on Mac, removing the `go up` command.

**Comment by zainengineer** [comment]
Thanks :)

**Comment by zainengineer** [comment]
![image](https://user-images.githubusercontent.com/4746235/74993393-f3331a80-549e-11ea-93df-d340d9c6d199.png)
![image](https://user-images.githubusercontent.com/4746235/74993426-080fae00-549f-11ea-9da2-79ab77603f01.png)

label is not defined for comand according to this error. can you hard code put isMac to true to check how it behaves on your system.

**Comment by zainengineer** [comment]
thanks for your help @ondras

**Comment by ondras** [comment]
Dang, must have made a mistake then.

**Comment by ondras** [comment]
Shall be fixed now.

**Comment by zainengineer** [comment]
yes works Thans for your patience
@ondras
