### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by torfhub** [ondras/my-mind#119]
how to run it?

**Comment by ondras** [comment]
I suggest downloading or cloning the application and opening it in the web browser. Alternatively, you can use the publicly hosted demo version at https://my-mind.github.io/

**Comment by torfhub** [comment]
how to run it offline, plese help !

**Comment by ondras** [comment]
There is no requirement to be online. Just download or clone the application and open it in the web browser.

**Comment by Fahim-Titan** [comment]
Clone the project or download the project. Click on the index.html. It should open in a browser.
