### ISSUE TITLE
MyMind and connections toward cloudflare and googletagmanager

### ISSUE THREAD

**Issue by benares42** [ondras/my-mind#120]
Hi,

I wish to propose MindMapping application but it has been raised to my attention that MyMind could be problematic because of of connections toward cloudflare.com or googletagmanager.com. Is there a way to configure or block this behavior without impairing the application itself? Could it be an enhancement?

Regards.

**Comment by ondras** [comment]
There is no hard dependency on these services. In particular:

  - cloudlfare.com is used as a CDN for icon hosting; you are free to download these and use your own storage

  - googletagmanager.com is used for analytics of the publicly hosted demo version; feel free to remove or replace for your own installation

**Comment by benares42** [comment]
Thank you for answer!
