### ISSUE TITLE
Save as -> Image leads to error

### ISSUE THREAD

**Issue by ttntm** [ondras/my-mind#122]
Hi, just wanted to use image export for a rather large map (~1850 lines).

All I'm getting is a new tab with the following error:

> This site can’t be reached
> The webpage at https://my-mind.github.io/ might be temporarily down or it may have moved permanently to a new web address.
> ERR_HTTP2_PROTOCOL_ERROR

My connection is fine and there are no error or anything in the DevTools.

Can provide my *.mymind file if that'd be helpful - just let me know.

**Comment by ondras** [comment]
Well, this is expected. Image rendering is a server-side task and there is currently no server available to perform it. See also: https://github.com/ondras/my-mind/issues/90

**Comment by ttntm** [comment]
Now that you said it, it should probably have occurred to me based on the URL 😅

Sorry to have bothered you and thanks for getting back to me.

**Comment by ondras** [comment]
> Sorry to have bothered you and thanks for getting back to me.

Well no problem. I am not happy with the status quo, but I have no time to undertake the complete refactoring in order to enable client-side image saving :-(

**Comment by neotamizhan** [comment]
Hello, 

Will this library be of use in client side image generation? 

https://github.com/niklasvh/html2canvas

**Comment by ondras** [comment]
Exporting images should work once again! See #134 for more info.
