### ISSUE TITLE
OnChange Event Callback

### ISSUE THREAD

**Issue by brunoinds** [ondras/my-mind#123]
There is a way to dispatch an event when something in the map changes? Like, shape, text, position...

```
MM.App.onChange = () => {
     //do something
}
```

**Comment by ondras** [comment]
Hi @brunoinds,

there is no such thing. If you wish to "listen" to stuff happening inside the app, hooking into (i.e. rewriting with a proxy) the `MM.App.action` might be a good way. I think that every primitive operation (i.e. every `MM.Action` instance) goes through this function.

**Comment by ondras** [comment]
The new `pubsub` module is the proper way to listen for changes. I believe that all changes generate the `"item-change"` message sent via the PubSub.
