### ISSUE TITLE
If you insert a sibling at the very root element (=as your first action) it behaves like a child

### ISSUE THREAD

**Issue by sztan** [ondras/my-mind#125]
everything is in the description

**Comment by ondras** [comment]
Yes, that is by design (and intentional, see https://github.com/ondras/my-mind/blob/master/src/command.js#L57) - the root element cannot have siblings. There is only one root.

**Comment by sztan** [comment]
I understand that there can only be one root element, I just wanted to try :-) Thx for your answer !
