### ISSUE TITLE
Do you have any development documents？Do you have a Chinese version？

### ISSUE THREAD

**Issue by wangzhihong1** [ondras/my-mind#135]
Thank you very much

**Comment by wangzhihong1** [comment]
development specification

**Comment by ondras** [comment]
Obtaining which data? This app allows *you* to create *your* mind maps based on *your* input (from *your* head). The data you use is not sourced from anywhere else :)

**Comment by wangzhihong1** [comment]
Excuse me，There is view only mode？I mean uneditable state

**Comment by wangzhihong1** [comment]
How to make "my-mind" not editable, only view

**Comment by ondras** [comment]
> Excuse me，There is view only mode？I mean uneditable state

No, there is no such feature. But I am currently working on the "image export" feature so you can save the map as a non-editable image.

**Comment by ondras** [comment]
> currently working

Yes, I am *currently working* on that feature. It is not ready at the moment. Please see and read https://github.com/ondras/my-mind/issues/134 for more information.

**Comment by ondras** [comment]
Exporting images shall work now.
