### ISSUE TITLE
How to get the map in json format without saving the map ?

### ISSUE THREAD

**Issue by clodion** [ondras/my-mind#137]
I would like to program a "save" button, which will save the map into a mysql database. the format will be json and the UI will not prompt any choice.

But after several trials I can't :    
- set the save format to json programmatically (ie without choosing it in the UI )
- get the json source of the map. 

Has somebody already done the same ?

**Comment by ondras** [comment]
The rewriting is done. We can continue this conversation.

**Comment by clodion** [comment]
thanks for your rewriting, it is a great job. Thanks to it, i have been able to display menu in another structure very easily. Here are two example of the redrawing :

![image](https://user-images.githubusercontent.com/21017246/139719885-eb58b716-e7c1-4d9a-b758-db3e62124b7c.png)
![image](https://user-images.githubusercontent.com/21017246/139719988-efd0c2a7-da58-4782-a8f6-a21bec00438a.png)

But i still can figure out how to get the json file or to create a command to get the json file in order to save it via ajax or to send it via websocket in order to make the map collaborative. Do you have a clue ?

**Comment by ondras** [comment]
So, the current map data:

```
import * as app from "./my-mind.js";

let data = app.currentMap.toJSON();
```

...this will give you the jsonified map data (as a JS object). If you want a string, you can either call `JSON.stringify`, or use the `native` formatter:

```
import { repo as formatRepo } from "./format/format.js";

let str = formatRepo.get("native").to(data);
```

**Comment by clodion** [comment]
Hi! thanks so much, 

with your code, I finally understood how to reach the datas inside your code : here is the code to add a command for those who are trying to do the same : 

  // ==========================================
  // commande to save the map in json format
  // ==========================================


  new class saveDirect extends Command {

    constructor() { 
  
    super("saveDirect", find_map_label("save"));
    this.keys = [{ code: "KeyS", ctrlKey: true, shiftKey: false }];

    }

    execute() { 
      
      let data = currentMap.toJSON()

      let str = repo6.get("native").to(data);

      [ ... Do you saving stuff with str ...]
    
    }

  }

To launch this function, just add a button on your application (index.html)  : 

<button class="yourPersonalCssClass" data-command="saveDirect" title="Save"><i class="fa fa-save"></i></button>


the function find_map_label(label) is for internationalization od the mindmap : here is the code used :  
(code to insert before line 10 of mindmap.js) 

  var mapLanguage='fr'; // contains the abbreviation for the language
 
 // the json for the language variable
// all the variables are not translated , just the one usefull for my project
// but one can add as many variable as needed

  var map_i18N = {
    "fr" : {  "insert-child" : "Insérer un enfant",
              "insert-sibling" : "Insérer un frère/soeur",
              "delete" : "Effacer un élément",
              "swap" :  "Intervertir un cousin",
              "side" : " Change le côté",
              "save" : "Enregistrer la carte",
              "save-as" :  "Enregistrer sous\u2026",
              "load" : "Charger une carte",
              "center" :  "Centrer la carte",
              "new" : "Nouvelle carte", 
              "renew" : "Efface la carte actuelle et en démarrer une nouvelle?",
              "zoom-in" : "Agrandir",
              "zoom-out" : "Rétrécir",
              "help" : "Montre/cache l'aide", 
              "ui" : "Montre/Cache l'interface utilisateur",
              "pan" : "Déplacer la carte",
              "fold" : "Plier", 
              "select-parent" : "Sélectionner le parent", 
              "edit" : "éditer l'élément",
              "finish" : "Terminer l'édition",
              "my_mind" : ":: my Mind",
              "newline" : "Nouvelle ligne",
              "cancel " : "Annuler",
              "bold" : "Gras",
              "underline" : "Souligné",
              "italic" : "Italique",
              "strikethrough" : "Barré",
              "value" : "Fixer une valeur",
              "yes" : "Oui",
              "no" : "Non",
              "computed" : "Calculé",
              "redo" : "Refaire",
              "undo" : "Défaire",
              "set-item-value" : "Fixer une valeur",
              "label-root" : "Ma carte mentale",
              "label-navigation" : "Navigation",
              "label-manipulation" : "Manipulation",
              "label-editing" : "Editer",
              "label-other" : "Autres",
              "label-help" : "Aide",
              "notes" : "Notes"
           }
  }
 
  function find_map_label(label, language) {

    var translated_label=""

    for (const [key, value] of Object.entries(map_i18N)) {

      if (key==language) { 
        
         var translation = value;

         for (const [key2, value2] of Object.entries(translation)) {

          // console.log(`${key2}: ${value2}`);
    
          if (key2==label) translated_label = value2
        }         


      }

    }

    return translated_label
    
  }

Everywhere there is a string to translate, you just  have to change the string with the code : find_map_label("label_to_translate", mapLanguage), an example  : 


  // .js/command/edit.js
  new class Edit extends Command {
    constructor() {
      super("edit", find_map_label("edit",mapLanguage));
      this.keys = [
        { code: "Space" },
        { code: "F2" }
      ];
    }
    execute() {
      startEditing();
    }
  }();
