### ISSUE TITLE
Nex coding - svg drawing inverted in th Tree layout -> left option

### ISSUE THREAD

**Issue by clodion** [ondras/my-mind#143]
When displaying the map with the TREE layout, option LEFT, the drawing keep the right corner draw - an image is best to understand : 
![image](https://user-images.githubusercontent.com/21017246/139802107-ef376bca-9452-4449-b31b-c79a89fc4fd0.png)

**Comment by ondras** [comment]
Yep, definitely a bug. Thanks for reporting!
