### ISSUE TITLE
Keyboard input is intercepted by mindmap when editing text in file menu field

### ISSUE THREAD

**Issue by rosensvv** [ondras/my-mind#145]
I cannot enter a WebDAV URL to open or save a file because any input is hijacked by the map. Pasting results in my URL being sent to the mind map as a node, typing any of the special characters like wasd executes their actions. I can only type using unused characters and therefore cannot enter .mymind extension to open and save my files properly. My setup is serving the website over a simple nginx configuration, hoping that I can save and load from WebDAV.

**Comment by ondras** [comment]
Sorry for that, should be fixed now.

**Comment by rosensvv** [comment]
It doesn't appear to be fixed on my end, am I supposed to do something other than redownload the repo?

**Comment by ondras** [comment]
> I had to restart my webserver and everything, appears to be fixed, thank you very much!

Probably caching issue. Glad to be of help!
