### ISSUE TITLE
"No" icon does not display when reloading json saved map

### ISSUE THREAD

**Issue by clodion** [ondras/my-mind#151]
Hi Ondras,

When reloading the map saved under the "native" format, the red cross icon "No" does not display whereas the "Yes" (a green checked icon) displays very well

Here is my code to do it : 
let json = format.from(txt);
this.loadDone(json);

**Comment by ondras** [comment]
This link: https://my-mind.github.io/?url=examples%2Ffeatures.mymind shows loading a previously saved native/json map. The "No" icons seem to be loaded/displayed just ok.

Can you be more specific with your report? Point me to an URL where the problem exists? Or explaining in more detail where is the code you use located?

**Comment by clodion** [comment]
In fact it seems to be in the json saved file, the status is saved with 'true' but does not saves for 'false', here the saved map in json  (native format) 

the json file : 
`{
	"root": {
		"id": "xgcsujhn",
		"text": "Ma carte mentale",
		"notes": "",
		"value": 12,
		"layout": "graph-bottom",
		"children": [
			{
				"id": "loyqlhur",
				"text": "child here ici<br>",
				"notes": "",
				"side": "right",
				"children": [
					{
						"id": "axxwmkjn",
						"text": "Test<br>",
						"notes": "",
						"textColor": "#8c1957"
					},
					{
						"id": "kpmmsfmq",
						"text": "a new child<br>",
						"notes": ""
					}
				]
			},
			{
				"id": "gfwxmfhg",
				"text": "test la<br>",
				"notes": "",
				"side": "left",
				"color": "#ce2480",
				"children": [
					{
						"id": "yauwpyqw",
						"text": "Test here<br>",
						"notes": "",
						"status": true
					}
				]
			}
		]
	}
}
`
and the corresponding map
![image](https://user-images.githubusercontent.com/21017246/147882865-9d887482-0923-4d77-85a4-9b2e3789f01a.png)

**Comment by ondras** [comment]
A-ha, okay. Will investigate.

**Comment by ondras** [comment]
Should be fixed now. Thanks @clodion for reporting!
