### ISSUE TITLE
webdav backend should not error on return code 201

### ISSUE THREAD

**Issue by melvincarvalho** [ondras/my-mind#171]
The current implementation of the webdav backend used in MyMind throws an error when it receives a 201 HTTP status code. However, this can cause unnecessary frustration for users when they create a new file or folder, as the 201 code indicates that the request has been successful.

To fix this issue, we can modify the code in line 25 of [webdav.ts](https://github.com/ondras/my-mind/blob/1195732cb39ea6dfeae741db0cdfb6e58dd9c476/src/backend/webdav.ts#L25) to allow for a 201 status code without throwing an error. This will improve the user experience and prevent confusion.

```JavaScript
if (response.status == 200) {
```

```JavaScript
if (response.status == 200 || response.status == 201) {
```

I can PR this if I have some guidance as to how you prefer changes, and releases to my-mind.js etc.

**Comment by ondras** [comment]
We can be even less strict here: any 2xx is a success. So perhaps this property is the correct way to go? https://developer.mozilla.org/en-US/docs/Web/API/Response/ok

**Comment by melvincarvalho** [comment]
Oh yes, even better.  I didnt even know about this mozilla magic!
