### ISSUE TITLE
How do increase distance between two item?

### ISSUE THREAD

**Issue by bin-san** [ondras/my-mind#179]
Small distances makes it congested. How do I increase The distance between two items? Default distance is too small. Plz tell me the way to do it. I will implement it.

**Comment by ondras** [comment]
Hi @bin-san ,

I would say that the SPACING_RANK constant at https://github.com/ondras/my-mind/blob/master/src/layout/graph.ts#L6 would be a good place to start.

**Comment by bin-san** [comment]
Thank you so much. I went through each line of your 4k lines of code. Its extremely well written, and you were confident of what you are doing and your dedication. This code inspires me as a beginner.

**Comment by bin-san** [comment]
Closing this issue as My confusions are cleared now.
