### ISSUE TITLE
Could it be possible to have a backup to store mind map on ownCloud ?

### ISSUE THREAD

**Issue by nVir** [ondras/my-mind#39]
Nice tool !

Instead of using GDrive, do you think that's could be possible to add a new backend which allow the user to edit from and store mind maps to ownCloud ?

Greetings,
 Alain

**Comment by anmol26s** [comment]
It does not work with Nextcloud. The webdav link says `This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.` I have both nextcloud and my-mind on the same domain.

**Comment by ondras** [comment]
Can you show a dump of HTTP requests related to saving your Mindmap to Nextcloud?

**Comment by anmol26s** [comment]
I get this error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://domain.tld/remote.php/webdav/maps/My%20Mind%20Map.mymind. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by ondras** [comment]
Okay, so this means that the remote side (your Nextcloud server) is not sending proper CORS headers. But you stated that you have both applications on the same domain? This looks like a cross-domain request.

**Comment by anmol26s** [comment]
Yes  
nextcloud is on nextcloud.domain.tld  and mindmap is on map.domain.tld . Can I set CORS in nextcloud?

**Comment by ondras** [comment]
For the purpose of the [Origin check](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), `nextcloud.domain.tld` and `map.domain.tld` are different domains.

As far as CORS support in Nextcloud is concerned, I have no idea. But it looks like someone already requested that: https://github.com/nextcloud/server/issues/3131
