### ISSUE TITLE
Why the item's text can not be select? I want a feature likes the picture: 

### ISSUE THREAD

**Issue by shatle** [ondras/my-mind#59]
![v1](https://cloud.githubusercontent.com/assets/1129872/9003872/5a6d2532-37a4-11e5-98a0-0ce78a52187b.gif)

---------

I want to select item's text using mouse, and delete by keyboard. 
I test in a simple contenteditable element that should be work, but item's text.

Sorry, I am poor for the repo. Who can tell me the reason? Conflict with the MoveItem?

Thanks!

**Comment by ondras** [comment]
This looks like a reasonable feature. I will have a look at the code to see how easily is this doable.

**Comment by ondras** [comment]
Shall be fixed now. Please confirm if the issue is gone.

**Comment by shatle** [comment]
Good, Thanks!
