### ISSUE TITLE
loading map in a variable

### ISSUE THREAD

**Issue by rvargas123** [ondras/my-mind#61]
hi, i need your help

I have a data.html page and within it have declared one text variable with a string json

I would like to know how I can load the map found on the page data.html passing it as a parameter?

var text = '{
 "root": {
  "id": "cdwflfdt",
  "text": "Case",
  "layout": "map",
  "children": [
   {
    "id": "wqjbgfpo",
    "text": "Case 1",
    "side": "right",
    "children": [
     {
      "id": "fmnjatve",
      "text": "Case 1.1"
     }
    ]
   },
   {
    "id": "bopfbkcw",
    "text": "Case 2",
    "side": "right"
   }
  ]
 }
}'

Thanks

**Comment by ondras** [comment]
Hi,

```js
var data = JSON.parse(text);
var map = MM.Map.fromJSON(data);
MM.App.setMap(map);
```

**Comment by ondras** [comment]
But this works only if your `text` variable is defined in the same page that hosts the My Mind application. If you have the My Mind app hosted elsewhere, you have to use the built-in save/load feature, that offers a set of loadable endpoints -- including local files, URLs etc.
