### ISSUE TITLE
my-mind.js 2844 .createDocument(null, null) error

### ISSUE THREAD

**Issue by 52manhua** [ondras/my-mind#63]
var doc = document.implementation.createDocument(null, null);

Firefox error:
 NS_ERROR_XPC_NOT_ENOUGH_ARGS: Not enough arguments @ http://xxxxx/my-mind.js:2844

can't save to freemind style

**Solve:**
Change to 
`var doc = document.implementation.createDocument("","", null);`

**Comment by ondras** [comment]
@52manhua interesting, can you please post your Firefox version?

**Comment by 52manhua** [comment]
@ondras   firefox 17.0

**Comment by ondras** [comment]
I see, this is supported from 26 upwards (see table at the bottom of https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createDocument). Will fix it for you :)

**Comment by ondras** [comment]
Should be fixed now. @52manhua, can you please test and confirm?

**Comment by 52manhua** [comment]
yeah, Can see the result,
but didn't download, maybe the firefox 17 is too old to do this~
thx
