### ISSUE TITLE
节点内容格式

### ISSUE THREAD

**Issue by ice-bin-ux** [ondras/my-mind#67]
节点内容怎么支持html呢？谢谢

**Comment by ondras** [comment]
Hi @ICE2017,

rudimentary HTML editing is supported via Ctrl+B/I/U/S commands that toggle bold/italic/underline/strikethrough on and off. And you are free to paste any _rich_ content when editing a node, since the node uses the `contenteditable` HTML attribute to act as a wysiwyg editor.
