### ISSUE TITLE
Release versions for the software

### ISSUE THREAD

**Issue by anmol26s** [ondras/my-mind#69]
Hi
I am packaging an installation script(for My-Mind,of course) for the[ YunoHost server.](https://yunohost.org) It requires to check the sha256sum of the sources before installing it, [see here](https://github.com/YunoHost-Apps/my-mind_ynh/blob/ynh_test/conf/app.src). Every time the master branch will get updated the checksum will be changing and the script will break. It would be nice if you can start to release versions, so that its easy to manage it as a package for the installation.

**Comment by ondras** [comment]
Okay, I just created a release. Is everything okay now?

**Comment by anmol26s** [comment]
Yes it is! Thank you.
