### ISSUE TITLE
Can not load saved json format file

### ISSUE THREAD

**Issue by wishWinds** [ondras/my-mind#71]
When I save the mind to the local while using file -> json. (click the save btn).  the browser show the base64 decoded text. I save these text to a file. and I can see the json text. 

But, when I load again the json text. the mind can not parse it correctly. the node show the meta data like "id" in the mind.

**Comment by ondras** [comment]
Please, what is your browser and its version?

**Comment by wishWinds** [comment]
Safari. 11.0.2

2018-01-08 1:32 GMT+08:00 Ondřej Žára <notifications@github.com>:

**Comment by ondras** [comment]
Okay, @wishWinds, would you please post the resulting JSON file somewhere? This will help us determine whether the problem is in the saving phase or in the loading phase.

**Comment by wishWinds** [comment]
Hi, like this.

```
{
	"root": {
		"id": "ufhfhfll",
		"text": "单词本<br>",
		"layout": "graph-right",
		"children": [
			{
				"id": "hpcvihxf",
				"text": "收集<br>",
				"side": "right",
				"children": [
					{
						"id": "gctecify",
						"text": "单词<br>"
					},
					{
						"id": "svkuemil",
						"text": "图片源<br>"
					},
					{
						"id": "frqgazur",
						"text": "翻译(自动化 google 命令行翻译)<br>"
					}
				]
			},
			{
				"id": "cdqeqrbo",
				"text": "回忆<br>",
				"side": "left",
				"children": [
					{
						"id": "spbmrbfr",
						"text": "单词<br>"
					},
					{
						"id": "jjfascce",
						"text": "翻译<br>"
					},
					{
						"id": "yeiticqx",
						"text": "图片源回溯<br>"
					}
				]
			},
			{
				"id": "zsswxege",
				"text": "练习<br>",
				"side": "right",
				"children": [
					{
						"id": "kaifdxed",
						"text": "给定一周生词, 进行文章练习<br>"
					}
				]
			}
		]
	}
}

```

**Comment by wishWinds** [comment]
the load result is here:

https://xyz.fancyjohn.com:5002/photo/share/wStEfRZf/photo_5368617265_6d792d6d696e64206572726f722e706e67

**Comment by wishWinds** [comment]
@ondras Hi, I have found the problem. The reason is safari don't download the file when I saved. I save the text with `.txt` extension. when I change to `.mymind`. everything goes right. 

Thanks !
