### ISSUE TITLE
very impressive software- how tricky to link API to JSON/XML file format ?

### ISSUE THREAD

**Issue by tony-shannon** [ondras/my-mind#72]
Well done on an excellent piece of work
I have a related question.
If we are working with information models that are persisted in a JSON/XML type format that has nothing to do with mindmaps, but wanted to expose some of the models as mindmaps..
is there an API specification to aim towards that would then allow your mindmaps to be an alternative view on these models?
thanks for any ideas'/suggestions..
Tony

**Comment by ondras** [comment]
As far as I know, there is no standard available for this. Mind Maps are hierarchical data structures by definition, which also holds for both JSON and XML, so at the end of the day these all are somewhat interchangeable. But there is no official "mind map" format, most mind mapping applications have their own.

**Comment by tony-shannon** [comment]
many thanks Ondras
Understood.
Can I ask how to examine the JSON that I assume populates mindmaps within this application then.
For instance how to find & explore the JSON that underpins the example mindmap?
http://my-mind.github.io/?url=examples%2Ffeatures.mymind
If we can understand the target JSON we may be able to work out how to target the format.
thanks again
Tony

**Comment by melvincarvalho** [comment]
@tony-shannon try saving it to localStorage then inspect in the console

Or save to a file and look at that

e.g.

> localStorage.getItem('mm.map.svorcklq')

```json
{
	"root": {
		"id": "svorcklq",
		"text": "My Mind Map",
		"layout": "map",
		"children": [
			{
				"id": "ocpfuugn",
				"text": "test1",
				"side": "right",
				"children": [
					{
						"id": "jmpgfdqx",
						"text": "test2"
					}
				]
			}
		]
	}
}
```

**Comment by melvincarvalho** [comment]
Note to self:  small mind maps could actually fit in a query string.

Some markdown editors do this

Ideally you'd use this in conjunction with a URL shortener too
