### ISSUE TITLE
change item html

### ISSUE THREAD

**Issue by zbiki** [ondras/my-mind#84]
Hello,
i want add a category on the root-item in my map.
i have create three files (attached) and edit the item.js 

`this._category = 0`
`category: document.createElement("span")`
`this._dom.category.classList.add("category");`
`this._dom.node.appendChild(this._dom.category);`

all works fine, but:

i must change the item.js file, i dont like this.
how can i add this without change the item.js? 
exists a method want can help me?

[action.cz.flag.js.txt](https://github.com/ondras/my-mind/files/2548698/action.cz.flag.js.txt)
[command.cz.flag.txt](https://github.com/ondras/my-mind/files/2548699/command.cz.flag.txt)
[item.cz.flag.txt](https://github.com/ondras/my-mind/files/2548700/item.cz.flag.txt)

mfg
Christian

**Comment by zbiki** [comment]
so, i remove all category stuff from item.js and change in the item.cz.flag.txt the setCategory Function to:
`MM.Item.prototype.setCategory = function (category) {
    this._category = category;

if (!this._dom.category) {
        this._dom.category = document.createElement("span");
        this._dom.category.classList.add("category");
        this._dom.content.appendChild(this._dom.category);
}
    this.updateCategory();
    return this.update();
};`

now i have in all new Items the span element  what i want. step by step

**Comment by zbiki** [comment]
ok, the only wa to override my-mind core Methods is: write my own file, put a Method with same name inside an build the mymind.js.
so i have all updates from git an me own changes.
thx for reading :)

**Comment by ondras** [comment]
Probably no longer relevant.
