### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by anmol26s** [ondras/my-mind#86]
Hi
There are some fixes which have not reached to people using version tag. On Yunohost we have the version 1.0. Would it be possible to have a new release?

**Comment by ondras** [comment]
Do I understand that all you need now is a version bump via a git tag?

**Comment by anmol26s** [comment]
Yes, a new tag would help the sources for the Yunohost to be updated.

**Comment by ondras** [comment]
@anmol26s thanks for the prompt response, going to tag asap.

**Comment by ondras** [comment]
Just pushed https://github.com/ondras/my-mind/releases/tag/v1.1 .

**Comment by anmol26s** [comment]
Thanks

**Comment by anmol26s** [comment]
Can you please publish a new version for my-mind please?

**Comment by ondras** [comment]
Thanks for the suggestion, I just pushed a `v1.2` tag.

**Comment by anmol26s** [comment]
Thanks
