### ISSUE TITLE
is it possible to extract or export in PDF

### ISSUE THREAD

**Issue by arabakevin** [ondras/my-mind#99]
Hi, 
I would like to know if it's possible to export in PDF ?
The export of the pictures in .png not working.
![Screen Shot 2019-09-25 at 14 23 21](https://user-images.githubusercontent.com/16837548/65600331-39438b00-dfa0-11e9-954d-f47eedb26318.png)

Thanks.
Best regards.
kevin

**Comment by ondras** [comment]
Please see https://github.com/ondras/my-mind/issues/90 for explanation.

I am currently thinking about re-implementing the Mind Map renderer exclusively via <canvas>; this would somewhat limit the amount of HTML formatting, but would result in the ability to create/download images directly in the browser.

**Comment by arabakevin** [comment]
Hi,
Thanks for the information.

**Comment by ondras** [comment]
Might be relevant: https://github.com/ondras/my-mind/wiki/Saving-images-client-side

**Comment by arabakevin** [comment]
thanks a lot.
